### ISSUE TITLE
Failure of stateful_open() keeps LIBRARY_IN_USE as true

### ISSUE THREAD

**Issue by koutheir** [Michael-F-Bryan/stateful-native-library#1]
In the implementation of `Library::new()`, if `bindings::stateful_open()` fails, then an error is immediately returned by `into_result()`, but the `LIBRARY_IN_USE` flag will stay set to `true` representing that the library is currently in use, which is not the correct state.

[Code](https://github.com/Michael-F-Bryan/stateful-native-library/blob/a1398c88de448bea9b7b76ee13e19fb1f4916dbd/src/lib.rs#L111):
```rust
impl Library {
    pub fn new() -> Result<Library, Error> {
        if LIBRARY_IN_USE.compare_and_swap(false, true, Ordering::SeqCst)
            == false
        {
            unsafe {
                bindings::stateful_open().into_result()?; // FIXME!
            }

            Ok(Library {
                _not_send: PhantomData,
            })
        } else {
            Err(Error::AlreadyInUse)
        }
    }
    // ...
```

Instead of using the `?` operator to return immediately, an explicit check should be done, in order to set `LIBRARY_IN_USE` to `false` in case `bindings::stateful_open()` fails.

Code:
```rust
impl Library {
    pub fn new() -> Result<Library, Error> {
        if LIBRARY_IN_USE.compare_and_swap(false, true, Ordering::SeqCst)
            == false
        {
            let result = unsafe {
                bindings::stateful_open().into_result().map(|_| Self { _not_send: PhantomData })
            };

            if result.is_err() {
                LIBRARY_IN_USE.store(false, Ordering::SeqCst);
            }

            result
        } else {
            Err(Error::AlreadyInUse)
        }
    }
    // ...
```

**Comment by Michael-F-Bryan** [comment]
Nice work spotting this @koutheir. I guess you can tell I didn't test the failing case properly, can't you :stuck_out_tongue:

**Comment by koutheir** [comment]
You're welcome! Thanks a lot for the article.
